# Локализация
locale:
  help:
    - '&aПомощь по плагину &b&lKingMountain&a:'
    - '&b/kingmountain - страница помощи'
    - '&b/kingmountain startpos - установить место телепорта'
    - '&b/kingmountain winpos - установить место куда нужно встать, чтобы ожидать победы'
    - '&b/kingmountain start - запустить ивент'
    - '&bАвтор плагина: &b&lKostyanDeveloper'
  noperms: '&cУ Вас недостаточно прав'
  winner: '&aИгра окончена! Выиграл <winner>!'
  timetowin: '&aВы достигли верха горы! Вы должны простоять <second> секунд, чтобы выиграть'
  youwin: '&aВы выиграли и получили ничего! Поздравляем!'
  started: '&aВнимание! Начался ивент "Король горы"! Чтобы телепортироваться на него используйте /gomp'
  startpos: '&aТочка старта успешно установлена!'
  winpos: '&aТочка победы успешно установлена!'
  teleported: '&aВы были телепортированы на точку мероприятия!'
  notstarted: '&cИгра не начата!'
# Сколько нужно стоять на горе. (в секундах)
seconds: 5
# Приз (команды приза)
prize:
  - 'lp user <winner> parent set admin'
  - 'tell <winner> Поздравляю Вы теперь админ!'
# не трогать (сохранение координат старта и победы)
location:
  start:
    x: 0
    y: 0
    z: 0
    world: world
  win:
    x: 0
    y: 0
    z: 0
    world: world
started: false